version: "1"

services:
  postgres:
    image: postgres:14
    restart: always
    container_name: postgresdb
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=eventmanagement
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
