# Generated by Django 5.0.1 on 2024-01-29 00:29

from django.db import migrations, models
from django.utils.text import slugify


def populate_slug_field(apps, schema_editor):
    Event = apps.get_model('event', 'Event')

    for event in Event.objects.all():
        event.slug = slugify(event.title)
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_online_alter_event_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(populate_slug_field)
    ]
